### ISSUE TITLE
How can I start the server ?

### ISSUE THREAD

**Issue by victorgrappe** [robertdale/tinkerpop-spring-boot#1]
Mr Dale,

I would like to create a new project using SpringBoot, TinkerPop and JanusGraph but I have trouble finding resources using both.
Your repository is the only source code I found so far and I think it could help me a lot if I can make it work.

I can build it successfully with maven: 
cd /Downloads/tinkerpop-spring-boot-master
mvn clean package

But when I try to start the server as usual:
java -jar ./tinkerpop-spring-boot/target/tinkerpop-spring-boot-0.0.2-SNAPSHOT.jar
java -jar ./tinkerpop-spring-boot-sample/target/tinkerpop-spring-boot-sample-0.0.2-SNAPSHOT.jar
java -jar ./tinkerpop-spring-boot-starter/target/tinkerpop-spring-boot-starter-0.0.2-SNAPSHOT.jar

I got the following error for each jar:
no main manifest attribute, in ./tinkerpop-spring-boot/target/tinkerpop-spring-boot-0.0.2-SNAPSHOT.jar

Even when I explicitely specify the Application class:
java -cp ./tinkerpop-spring-boot-starter/target/tinkerpop-spring-boot-starter-0.0.2-SNAPSHOT.jar com.github.robertdale.spring.boot.tinkerpop.sample.TinkerpopApplication
Error: Could not find or load main class com.github.robertdale.spring.boot.tinkerpop.sample.TinkerpopApplication

Did I miss something ?
Is there any documentation/resource I can use to make it work ?

Thank you in advance,

Victor

**Comment by robertdale** [comment]
This is just the client analogous to `spring-data-*`.  You need to download and start a server separately.
